//! Substrate parity, the SHA-256 known-answer vectors and the mandatory negative
//! control (REQ-30, REQ-34, REQ-35, REQ-38, section 3.6). Wired into the crate by
//! `lib.rs`'s `#[path = "../unit_tests/substrate_parity.rs"] mod substrate_parity;`
//! declaration (REQ-38): this file is compiled as an IN-CRATE module, not an
//! external crate, so it can reach `crate::record`, `crate::verify` and
//! `crate::authoriser`'s `pub(crate)` items directly, exactly as
//! `crates/boundary-gjoll/unit_tests/layer_one_parity.rs` reaches
//! `crate::rule::ConsequentialityVerdict::new` (D109 precedent).
//!
//! THIS FILE WILL FAIL TO COMPILE until `crate::sha256`, `crate::record`,
//! `crate::verify`, `crate::authoriser`, `crate::types` and `crate::cohort` exist
//! and are declared as modules from `lib.rs`. That is expected and correct at this
//! stage: this file and `lib.rs`'s test-wiring declaration are written before the
//! implementation, so the implementing agent builds the crate to satisfy a fixed,
//! already-written contract rather than the reverse (the same discipline D109's own
//! `layer_one_parity.rs` header states).
//!
//! Signatures assumed here, fixed as this test suite's own committed contract where
//! the spec's section 4.1 leaves the exact shape to the implementing agent:
//!
//!   - `sha256::digest_hex(&[u8]) -> String`, the crate's only public item in that
//!     module (REQ-3).
//!   - `record::AttestedRecord` (`pub(crate)`, no concrete record type named in the
//!     module, REQ-7): `record_type(&self) -> &'static str`,
//!     `canonical_fields(&self) -> Vec<(&'static str, String)>`.
//!   - `record::canonical_record_bytes<R: AttestedRecord>(record: &R) -> Vec<u8>`
//!     (REQ-8, REQ-9); `record::compute_record_attestation<R: AttestedRecord>(record:
//!     &R, secret: &[u8]) -> String` (REQ-11); `record::constant_time_equals(&str,
//!     &str) -> bool` (REQ-4). All three `pub(crate)`: REQ-13 forbids any PUBLIC
//!     function that takes secret bytes, so these live only where `unit_tests/` can
//!     reach them, never from `tests/`.
//!   - `verify::RecordRefusal` (re-exported publicly at the crate root, three
//!     variants: `Unattested(String)`, `UnknownAuthoriser(String)`,
//!     `DigestMismatch(String)`, mirroring `verify_record_attestation`'s three
//!     refusal branches, REQ-27) and `verify::verify_record<R: AttestedRecord>(record:
//!     &R, authoriser: Option<&str>, attestation: Option<&str>, trusted:
//!     &TrustedAuthoriserSet) -> Result<(), RecordRefusal>` (`pub(crate)`).
//!   - `authoriser::TrustedAuthoriserSet` has a `pub(crate)` field, `authorisers:
//!     HashMap<String, Vec<u8>>` (REQ-13), with no dedicated test constructor:
//!     fixtures build it directly via struct-literal syntax from within the crate,
//!     reachable only from `unit_tests/`.
//!   - `types::CohortDefinition { cohort_id: String, permitted_actions: Vec<String>,
//!     trust_ceiling: String, consequential_sinks: Vec<String>, authoriser:
//!     Option<String>, attestation: Option<String> }` implementing `AttestedRecord`
//!     (REQ-20; six fields, no `permitted_targets`).
//!   - `cohort::{COHORT_ID, PERMITTED_ACTIONS, TRUST_CEILING, CONSEQUENTIAL_SINKS,
//!     AUTHORISER_ID}`, compile-time constants (REQ-20).
//!
//! The vector file this suite replays,
//! `crates/hierarchy-vor/vectors/cohort_vectors.json`, does not exist at this
//! commit either (it is generated by `ontology/tools/export_cohort_vectors.py`,
//! files 14 and 16, both out of this agent's scope). Per EC-10, an absent vector
//! file is a FAILURE, never a skip: `load_vectors()` below panics with instructions
//! rather than silently reporting nothing to check.

use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

use crate::authoriser::TrustedAuthoriserSet;
use crate::cohort::{
    AUTHORISER_ID, COHORT_ID, CONSEQUENTIAL_SINKS, PERMITTED_ACTIONS, TRUST_CEILING,
};
use crate::record::{
    AttestedRecord, canonical_record_bytes, compute_record_attestation, constant_time_equals,
};
use crate::sha256::digest_hex;
use crate::types::CohortDefinition;
use crate::verify::{RecordRefusal, verify_record};

// ---------------------------------------------------------------------------------
// Vector-file fixture shapes (section 4.3's schema). TEST-side deserialisation
// targets only, never the crate's own types.
// ---------------------------------------------------------------------------------

#[derive(Deserialize)]
struct VectorFile {
    #[allow(dead_code)]
    schema_version: u32,
    #[allow(dead_code)]
    claim: String,
    #[allow(dead_code)]
    generated_from: GeneratedFrom,
    fixture_secret_hex: String,
    #[allow(dead_code)]
    fixture_secret_note: String,
    expected_count: u32,
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct GeneratedFrom {
    #[allow(dead_code)]
    authorisation_record_py_sha256: String,
    #[allow(dead_code)]
    sink_attestation_py_sha256: String,
}

#[derive(Deserialize)]
struct Vector {
    id: String,
    case: String,
    record_type: String,
    fields: Vec<(String, String)>,
    canonical_bytes_hex: String,
    attestation: Option<String>,
}

// ---------------------------------------------------------------------------------
// Fixture-loading helpers.
// ---------------------------------------------------------------------------------

fn vector_file_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("vectors")
        .join("cohort_vectors.json")
}

fn load_vectors() -> VectorFile {
    let raw = fs::read_to_string(vector_file_path()).unwrap_or_else(|e| {
        panic!(
            "substrate_parity: could not read \
             crates/hierarchy-vor/vectors/cohort_vectors.json ({e}); run \
             `python -m ontology.tools.export_cohort_vectors` from the repo root first \
             (EC-10: an absent oracle is not a passing oracle, so this is a hard \
             failure, never a skip)"
        )
    });
    let data: VectorFile = serde_json::from_str(&raw).unwrap_or_else(|e| {
        panic!("substrate_parity: cohort_vectors.json did not parse ({e}); EC-10: fail, never skip")
    });
    assert_eq!(
        data.vectors.len(),
        data.expected_count as usize,
        "cohort_vectors.json's own expected_count has drifted from its actual vector count"
    );
    data
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn decode_hex(s: &str) -> Vec<u8> {
    assert_eq!(
        s.len() % 2,
        0,
        "odd-length hex string in vector file: {s:?}"
    );
    (0..s.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&s[i..i + 2], 16)
                .unwrap_or_else(|e| panic!("invalid hex byte at offset {i} in {s:?}: {e}"))
        })
        .collect()
}

fn leak_str(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}

/// A generic `AttestedRecord` built from one vector's own `fields`, so the replay
/// exercises `record::canonical_record_bytes` and `record::compute_record_attestation`
/// exactly as the Python exporter's shim record does, without this crate's test code
/// reimplementing the encoding (REQ-28's discipline applied on the Rust side too).
struct VectorRecord {
    record_type: &'static str,
    fields: Vec<(&'static str, String)>,
}

impl AttestedRecord for VectorRecord {
    fn record_type(&self) -> &'static str {
        self.record_type
    }

    fn canonical_fields(&self) -> Vec<(&'static str, String)> {
        self.fields.clone()
    }
}

fn build_generic_record(v: &Vector) -> VectorRecord {
    VectorRecord {
        record_type: leak_str(v.record_type.clone()),
        fields: v
            .fields
            .iter()
            .map(|(name, value)| (leak_str(name.clone()), value.clone()))
            .collect(),
    }
}

/// The real hardcoded cohort's own content, built from `crate::cohort`'s constants
/// exactly as `crate::cohort::load_verified_cohort` must (REQ-20, REQ-22): used both
/// by the mandatory negative control below and by the "real cohort content" vector
/// cross-check, so both exercise the SAME construction path.
fn hardcoded_cohort_record() -> CohortDefinition {
    CohortDefinition {
        cohort_id: COHORT_ID.to_string(),
        permitted_actions: PERMITTED_ACTIONS.iter().map(|s| s.to_string()).collect(),
        trust_ceiling: TRUST_CEILING.to_string(),
        consequential_sinks: CONSEQUENTIAL_SINKS.iter().map(|s| s.to_string()).collect(),
        authoriser: Some(AUTHORISER_ID.to_string()),
        attestation: None,
    }
}

/// A secret used ONLY inside this file, never the real `heimdall-dev` secret
/// (section 2.2: mechanism parity is exercised under a fixture secret, everywhere,
/// on every machine). 40 bytes, comfortably over `authoriser::MIN_SECRET_BYTES`.
const FIXTURE_SECRET: &[u8] = b"vor-req34-mandatory-negative-control-fixture!!";

fn trusted_set_for_fixture_secret() -> TrustedAuthoriserSet {
    TrustedAuthoriserSet {
        authorisers: [(AUTHORISER_ID.to_string(), FIXTURE_SECRET.to_vec())]
            .into_iter()
            .collect(),
    }
}

// ---------------------------------------------------------------------------------
// REQ-34: the mandatory negative control, ordered BEFORE every positive assertion
// in this file, following `_bfo_relatedness_control_check`'s precedent (D101) that
// no check is trusted until it has been shown to bite.
// ---------------------------------------------------------------------------------

#[test]
fn req34_mandatory_negative_control_mutated_field_is_refused() {
    let mut record = hardcoded_cohort_record();
    let attestation = compute_record_attestation(&record, FIXTURE_SECRET);
    record.attestation = Some(attestation);

    // Positive sanity check, deliberately placed AFTER the mutation is prepared but
    // asserted before it is applied: the untouched, correctly attested record must
    // verify under the fixture secret before the control mutates anything.
    let trusted = trusted_set_for_fixture_secret();
    let sanity = verify_record(
        &record,
        record.authoriser.as_deref(),
        record.attestation.as_deref(),
        &trusted,
    );
    assert!(
        sanity.is_ok(),
        "sanity check failed before the negative control mutates anything: {sanity:?}"
    );

    // The control itself: mutate exactly ONE field after attestation, without
    // recomputing the digest, and assert refusal.
    record.trust_ceiling = "TRUSTED".to_string();
    let refused = verify_record(
        &record,
        record.authoriser.as_deref(),
        record.attestation.as_deref(),
        &trusted,
    );
    assert!(
        matches!(refused, Err(RecordRefusal::DigestMismatch(_))),
        "AC-34: mutating trust_ceiling after attestation must be refused with a digest \
         mismatch, not accepted; got {refused:?}"
    );
}

#[test]
fn req34_control_has_a_real_bite_not_a_tautology() {
    // AC-34's second clause: "when the control is inverted so that it expects
    // success, then the suite fails". Demonstrated here directly: the SAME mutated
    // record from the test above must produce an `Err`, so an inverted expectation
    // (`is_ok()`) is PROVABLY false, not merely unexercised.
    let mut record = hardcoded_cohort_record();
    let attestation = compute_record_attestation(&record, FIXTURE_SECRET);
    record.attestation = Some(attestation);
    record.trust_ceiling = "TRUSTED".to_string();

    let trusted = trusted_set_for_fixture_secret();
    let outcome = verify_record(
        &record,
        record.authoriser.as_deref(),
        record.attestation.as_deref(),
        &trusted,
    );
    assert!(
        outcome.is_err(),
        "negative control FAILED to bite: a mutated field verified successfully, so an \
         inverted (is_ok) expectation would have passed wrongly (AC-34)"
    );
}

// ---------------------------------------------------------------------------------
// REQ-35: SHA-256 known-answer vectors. Published values, computed independently
// with Python's `hashlib.sha256` (the substrate's own ground truth, section 2.3) and
// pinned literally here so this crate's implementation is checked against a fixed
// external oracle rather than against itself.
// ---------------------------------------------------------------------------------

#[test]
fn sha256_kat_empty_input() {
    assert_eq!(
        digest_hex(b""),
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );
}

#[test]
fn sha256_kat_single_block_input_abc() {
    assert_eq!(
        digest_hex(b"abc"),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
}

#[test]
fn sha256_kat_multi_block_input_nist_two_block_vector() {
    // The standard NIST two-block SHA-256 test vector.
    assert_eq!(
        digest_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
        "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
    );
}

#[test]
fn sha256_kat_boundary_55_bytes_leaves_no_room_for_padding_in_one_block() {
    // 55 bytes + the mandatory 0x80 padding byte + the 8-byte length field = 64
    // bytes exactly: the tightest input that still fits a single block.
    let input = vec![b'a'; 55];
    assert_eq!(
        digest_hex(&input),
        "9f4390f8d30c2dd92ec9f095b65e2b9ae9b0a925a5258e241c9f1e910f734318"
    );
}

#[test]
fn sha256_kat_boundary_56_bytes_forces_a_second_padding_block() {
    // One byte more and the 0x80 padding byte plus the 8-byte length no longer fit:
    // this input straddles the boundary REQ-35 names explicitly.
    let input = vec![b'a'; 56];
    assert_eq!(
        digest_hex(&input),
        "b35439a4ac6f0948b6d6f9e3c6af0f5f590ce20f1bde7090ef7970686ec6738a"
    );
}

#[test]
fn sha256_kat_boundary_64_bytes_exactly_one_full_block() {
    let input = vec![b'a'; 64];
    assert_eq!(
        digest_hex(&input),
        "ffe054fe7ae0cb6dc65c3af9b61d5209f439851db43d0ba5997337df154668eb"
    );
}

// ---------------------------------------------------------------------------------
// REQ-4: the crate's one constant-time digest comparison, exercised directly.
// ---------------------------------------------------------------------------------

#[test]
fn constant_time_equals_accepts_identical_and_rejects_differing_digests() {
    let a = "deadbeefdeadbeefdeadbeefdeadbeef".to_string();
    assert!(
        constant_time_equals(&a, &a),
        "an identical digest must compare equal"
    );
    assert!(
        !constant_time_equals(&a, "deadbeefdeadbeefdeadbeefdeadbeee"),
        "a single differing trailing character must not compare equal"
    );
    assert!(
        !constant_time_equals(&a, "deadbeefdeadbeefdeadbeefdeadbee"),
        "a shorter string must not compare equal (length checked first, REQ-4)"
    );
}

// ---------------------------------------------------------------------------------
// REQ-30: the golden-vector replay, comparing canonical BYTES first and the digest
// second (EC-9), so a byte-level divergence is localised to the vector rather than
// only surfacing as an opaque digest mismatch.
// ---------------------------------------------------------------------------------

#[test]
fn vector_replay_matches_python_export_bytes_then_digest() {
    let data = load_vectors();
    assert!(
        !data.vectors.is_empty(),
        "cohort_vectors.json carries no vectors at all"
    );

    for v in &data.vectors {
        let record = build_generic_record(v);
        let bytes = canonical_record_bytes(&record);
        let bytes_hex = hex_encode(&bytes);
        assert_eq!(
            bytes_hex, v.canonical_bytes_hex,
            "vector {} ({}): canonical bytes diverge from the Python export (EC-9); a \
             digest-only comparison would have hidden which field diverged (REQ-30)",
            v.id, v.case,
        );

        // The unattested vector (REQ-32 case 6) carries no attestation to replay.
        if let Some(expected_attestation) = &v.attestation {
            let fixture_secret = decode_hex(&data.fixture_secret_hex);
            let attestation = compute_record_attestation(&record, &fixture_secret);
            assert_eq!(
                &attestation, expected_attestation,
                "vector {} ({}): attestation diverges from the Python export under the \
                 committed fixture secret",
                v.id, v.case,
            );
        }
    }
}

#[test]
fn req12_all_vector_attestations_are_pairwise_distinct() {
    // REQ-12, AC-12: cross-type separation (a differing record-type tag yields a
    // differing digest for otherwise identical fields) and cross-substrate
    // separation (the same logical content attested through `sink_attestation`'s
    // own domain separator yields a differing digest) must both hold. Every emitted
    // vector's content differs from every other's by construction (REQ-32's nine
    // named cases are pairwise distinct scenarios), so this is checked as the
    // general "no two attestations collide" invariant, which subsumes both named
    // pairs without depending on their exact position in the file.
    let data = load_vectors();
    let attested: Vec<(&str, &str)> = data
        .vectors
        .iter()
        .filter_map(|v| v.attestation.as_deref().map(|a| (v.id.as_str(), a)))
        .collect();
    assert!(
        attested.len() >= 2,
        "need at least two attested vectors to demonstrate separation at all"
    );
    for i in 0..attested.len() {
        for j in (i + 1)..attested.len() {
            assert_ne!(
                attested[i].1, attested[j].1,
                "REQ-12: vectors {} and {} must not share an attestation digest \
                 (cross-type / cross-substrate separation)",
                attested[i].0, attested[j].0,
            );
        }
    }
}

#[test]
fn real_cohort_content_matches_crate_types_cohort_definition_encoding() {
    // REQ-32 case 1 ("the real cohort's exact content, attested under the fixture
    // secret"): cross-checked against `crate::types::CohortDefinition`'s OWN
    // `AttestedRecord` implementation, not only the generic `VectorRecord` double
    // every other vector uses, so this specifically proves the crate's real cohort
    // type encodes identically to the Python exporter's shim for this case.
    let data = load_vectors();
    let v = data
        .vectors
        .iter()
        .find(|v| {
            v.fields
                .iter()
                .any(|(name, value)| name == "cohort_id" && value == COHORT_ID)
        })
        .unwrap_or_else(|| {
            panic!(
                "no vector in cohort_vectors.json carries the real cohort_id {COHORT_ID:?} \
                 (REQ-32 case 1)"
            )
        });

    let record = hardcoded_cohort_record();
    let bytes = canonical_record_bytes(&record);
    assert_eq!(
        hex_encode(&bytes),
        v.canonical_bytes_hex,
        "crate::types::CohortDefinition's own canonical encoding of the real \
         heimdall-dev cohort diverges from the Python export for vector {}",
        v.id,
    );
}
